language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
install:
  - yarn --ignore-engines
script:
  - NODE_OPTIONS="--max-old-space-size=4096" yarn run dist
after_success:
  - NODE_OPTIONS="--max-old-space-size=4096" yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
